services:
  mysql:
    image: mysql
    ports:
      - "3300:3306"
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

volumes:
  mysql-data:
